# CircleCI configuration file
version: 2.1
orbs:
  node: circleci/node@5.0.2
jobs:
  lint_and_test:
    executor: node/default # use the default executor defined within the orb
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn run lint
          name: Lint Files
      - run:
          command: yarn test
          name: Run Tests
      - persist_to_workspace:
          root: .
          paths:
            - .