# CircleCI configuration file

version: 2.1

orbs:
  node: circleci/node@5.0.2
  codecov: codecov/codecov@3.1.1

workflows:
  version: 2
  build:
    jobs:
      - lint_and_test

jobs:
  lint_and_test:
    executor: node/default # use the default executor defined within the orb
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn run lint
          name: Lint Files
      - run:
          command: yarn run test
          name: Run Tests
      - codecov/upload:
          file: './coverage/clover.xml'